# Generated by Django 6.0.6 on 2026-07-02 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0001_initial'),
        ('producteur', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandepaddy',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commandes_paddy', to='producteur.stockpaddy'),
        ),
        migrations.AddField(
            model_name='produit',
            name='stock_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produits', to='administration.commandepaddy'),
        ),
    ]
