# Generated by Django 6.0.6 on 2026-07-02 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('prix', models.DecimalField(decimal_places=0, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='produits/')),
                ('stock', models.PositiveIntegerField(default=0)),
                ('poids_options', models.CharField(default='5kg,10kg,25kg', help_text='Options de poids séparées par des virgules', max_length=100)),
                ('tracable', models.BooleanField(default=True)),
                ('actif', models.BooleanField(default=True)),
            ],
        ),
    ]
