# Generated by Django 6.0.6 on 2026-07-01 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # LigneCommande référence Produit — maintenant dans l'app transformatrice_admin
        ('transformatrice_admin', '0002_commandepaddy_produit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=20)),
                ('adresse', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='CommandeClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(
                    choices=[
                        ('attente', 'En attente'),
                        ('preparation', 'En préparation'),
                        ('en_livraison', 'En livraison'),
                        ('livree', 'Livrée'),
                        ('annulee', 'Annulée'),
                    ],
                    default='attente',
                    max_length=20,
                )),
                ('mode_paiement', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='commandes',
                    to='client.client',
                )),
            ],
            options={
                'verbose_name': 'Commande client',
                'verbose_name_plural': 'Commandes clients',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='LigneCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commande', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='lignes',
                    to='client.commandeclient',
                )),
                ('produit', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name='lignes_commande',
                    to='transformatrice_admin.produit',
                )),
            ],
            options={
                'verbose_name': 'Ligne de commande',
                'verbose_name_plural': 'Lignes de commande',
            },
        ),
    ]
