# Generated by Django 6.0.6 on 2026-07-02 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandeclient',
            name='adresse_livraison',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='commandeclient',
            name='frais_livraison',
            field=models.PositiveIntegerField(default=2000),
        ),
        migrations.AddField(
            model_name='commandeclient',
            name='numero',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
