# Generated by Django 6.0.6 on 2026-07-02 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='categorie',
            field=models.CharField(choices=[('blanc', 'Riz Blanc'), ('parfume', 'Riz Parfumé'), ('complet', 'Riz Complet'), ('brisure', 'Brisure')], default='blanc', max_length=20),
        ),
    ]
