# Generated by Django 6.0.6 on 2026-07-03 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_commandeclient_adresse_livraison_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commandeclient',
            name='numero',
        ),
    ]
