# Generated by Django 6.0.6 on 2026-07-02 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_produit_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='nb_avis',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='produit',
            name='note',
            field=models.DecimalField(decimal_places=1, default=4.8, max_digits=3),
        ),
        migrations.AddField(
            model_name='produit',
            name='origine',
            field=models.CharField(default='Mbour, Sénégal', max_length=100),
        ),
        migrations.AddField(
            model_name='produit',
            name='points_forts',
            field=models.TextField(blank=True, default='Zéro pesticide chimique de synthèse\nTaux de brisure inférieur à 5%\nRiche en fibres naturelles et minéraux', help_text='Un point fort par ligne'),
        ),
        migrations.AddField(
            model_name='produit',
            name='producteur_info',
            field=models.CharField(default='Transformé par YEES NAA CONNECT à partir de paddy local.', max_length=255, verbose_name='Info producteur'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='poids_options',
            field=models.CharField(default='5kg,10kg,25kg', max_length=100),
        ),
    ]
