# Generated by Django 6.0.6 on 2026-07-03 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_remove_commandeclient_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandeclient',
            name='numero',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
