# Generated by Django 6.0.6 on 2026-07-04 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_commandeclient_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandeclient',
            name='frais_livraison',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
