# Generated by Django 6.0.6 on 2026-07-04 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_alter_commandeclient_frais_livraison'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandeclient',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commandeclient',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
