# Generated by Django 6.0.6 on 2026-07-01 21:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Producteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='producteur_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StockPaddy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variete', models.CharField(choices=[('blanc', 'Blanc'), ('parfume', 'Parfumé')], max_length=20)),
                ('quantite_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_par_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_recolte', models.DateField()),
                ('region', models.CharField(max_length=100)),
                ('statut', models.CharField(choices=[('disponible', 'Disponible'), ('commande', 'Commandé'), ('epuise', 'Épuisé')], default='disponible', max_length=20)),
                ('est_bio', models.BooleanField(default=False)),
                ('producteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='producteur.producteur')),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('type_riz', models.CharField(choices=[('blanc', 'Blanc'), ('etuve', 'Étuvé'), ('parfume', 'Parfumé')], max_length=20)),
                ('poids_kg', models.PositiveSmallIntegerField(choices=[(5, 'Cinq'), (10, 'Dix'), (25, 'Vingt Cinq')])),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_sacs', models.PositiveIntegerField(default=0)),
                ('code_lot', models.CharField(max_length=50, unique=True)),
                ('est_actif', models.BooleanField(default=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('stock_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produits', to='producteur.stockpaddy')),
            ],
        ),
        migrations.CreateModel(
            name='CommandePaddy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_commande', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_livraison', models.DateField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('confirmee', 'Confirmée'), ('recue', 'Reçue'), ('annulee', 'Annulée')], default='en_attente', max_length=20)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('commande_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commandes_paddy_passees', to=settings.AUTH_USER_MODEL)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commandes_paddy', to='producteur.stockpaddy')),
            ],
        ),
    ]
