# Generated by Django 6.0.6 on 2026-07-01 21:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Producteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='producteur_profile',
                    to=settings.AUTH_USER_MODEL,
                )),
            ],
        ),
        migrations.CreateModel(
            name='StockPaddy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variete', models.CharField(
                    choices=[('blanc', 'Blanc'), ('parfume', 'Parfumé')],
                    max_length=20,
                )),
                ('quantite_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_par_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_recolte', models.DateField()),
                ('region', models.CharField(max_length=100)),
                ('statut', models.CharField(
                    choices=[('disponible', 'Disponible'), ('commande', 'Commandé'), ('epuise', 'Épuisé')],
                    default='disponible',
                    max_length=20,
                )),
                ('est_bio', models.BooleanField(default=False)),
                ('producteur', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='stocks',
                    to='producteur.producteur',
                )),
            ],
        ),
    ]
