# Generated by Django 6.0.6 on 2026-07-02 03:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('producteur', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='commandepaddy',
            name='commande_par',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commandes_paddy_passees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='producteur',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='producteur_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockpaddy',
            name='producteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='producteur.producteur'),
        ),
        migrations.AddField(
            model_name='produit',
            name='stock_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produits', to='producteur.stockpaddy'),
        ),
        migrations.AddField(
            model_name='commandepaddy',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commandes_paddy', to='producteur.stockpaddy'),
        ),
    ]
