# Generated by Django 6.0.6 on 2026-07-02 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producteur', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockpaddy',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='stockpaddy',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='stocks_paddy/'),
        ),
    ]
