# Generated by Django 6.0.6 on 2026-07-02 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producteur', '0002_stockpaddy_description_stockpaddy_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockpaddy',
            name='photo',
            field=models.ImageField(upload_to='stocks_paddy/'),
        ),
    ]
