# Generated by Django 6.0.6 on 2026-07-02 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producteur', '0003_alter_stockpaddy_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockpaddy',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
